@echo off
setlocal
cd /d "%~dp0"
set "YT_QUARTUS="
if defined QUARTUS_ROOTDIR if exist "%QUARTUS_ROOTDIR%\bin64\quartus_sh.exe" set "YT_QUARTUS=%QUARTUS_ROOTDIR%\bin64\quartus_sh.exe"
if not defined YT_QUARTUS if exist "C:\intelFPGA_lite\17.0\quartus\bin64\quartus_sh.exe" set "YT_QUARTUS=C:\intelFPGA_lite\17.0\quartus\bin64\quartus_sh.exe"
if not defined YT_QUARTUS if exist "C:\intelFPGA\17.0\quartus\bin64\quartus_sh.exe" set "YT_QUARTUS=C:\intelFPGA\17.0\quartus\bin64\quartus_sh.exe"
if not defined YT_QUARTUS (
  echo Quartus 17.0.x was not found.
  echo Install Quartus Prime Lite 17.0 with Cyclone V support and the 17.0.2 update.
  echo Official MiSTer instructions:
  echo https://mister-devel.github.io/MkDocs_MiSTer/developer/mistercompile/
  echo For a custom installation, set QUARTUS_ROOTDIR to its quartus folder.
  pause
  exit /b 1
)
"%YT_QUARTUS%" --version > build.log 2>&1
findstr /C:"Version 17.0" build.log >nul
if errorlevel 1 (
  echo This project targets Quartus 17.0.x. Found a different version:
  type build.log
  pause
  exit /b 1
)
echo Compiling YouTubeCRT. This can take several minutes.
echo Detailed progress is written to build.log in this folder.
"%YT_QUARTUS%" --flow compile YouTubeCRT >> build.log 2>&1
if errorlevel 1 (
  echo Build failed. Send build.log so the error can be checked.
  pause
  exit /b 1
)
if not exist output_files\YouTubeCRT.rbf (
  echo Compilation ended but output_files\YouTubeCRT.rbf is missing.
  echo Send build.log.
  pause
  exit /b 1
)
rem Only remove files generated by this packaging script from previous runs.
if not exist build-result mkdir build-result
for %%F in (YouTubeCRT.rbf YouTubeCRT.sta.summary YouTubeCRT.sta.rpt YouTubeCRT.fit.summary YouTubeCRT.map.summary timing-check.txt build.log) do if exist "build-result\%%F" del /q "build-result\%%F"
if exist build-result.zip del /q build-result.zip
"%YT_QUARTUS%" -t check-timing.tcl > timing-check.txt 2>&1
set "YT_TIMING_STATUS=%ERRORLEVEL%"
copy /y build.log build-result\ >nul
copy /y timing-check.txt build-result\ >nul
for %%F in (output_files\YouTubeCRT.sta.summary output_files\YouTubeCRT.sta.rpt output_files\YouTubeCRT.fit.summary output_files\YouTubeCRT.map.summary) do if exist "%%F" copy /y "%%F" build-result\ >nul
if "%YT_TIMING_STATUS%"=="0" copy /y output_files\YouTubeCRT.rbf build-result\ >nul
powershell -NoProfile -Command "Compress-Archive -Path 'build-result\*' -DestinationPath 'build-result.zip' -Force"
if "%YT_TIMING_STATUS%"=="0" (
  echo Compilation and reported-slack check passed.
) else (
  echo Compilation completed, but the timing check did not pass.
  echo The result ZIP contains reports only. Do not use this RBF yet.
)
echo Send the NEW build-result.zip for review.
echo If ZIP creation failed, send build.log and timing-check.txt.
pause
exit /b %YT_TIMING_STATUS%
